var nameList = [
    "Time",
    "Past",
    "Future",
    "Dev",
    "Fly",
    "Flying",
    "Soar",
    "Soaring",
    "Power",
    "Falling",
    "Fall",
    "Jump",
    "Cliff",
    "Mountain",
    "Rend",
    "Red",
    "Blue",
    "Green",
    "Yellow",
    "Gold",
    "Demon",
    "Demonic",
    "Panda",
    "Cat",
    "Kitty",
    "Kitten",
    "Zero",
    "Memory",
    "Trooper",
    "XX",
    "Bandit",
    "Fear",
    "Light",
    "Glow",
    "Tread",
    "Deep",
    "Deeper",
    "Deepest",
    "Mine",
    "Your",
    "Worst",
    "Enemy",
    "Hostile",
    "Force",
    "Video",
    "Game",
    "Donkey",
    "Mule",
    "Colt",
    "Cult",
    "Cultist",
    "Magnum",
    "Gun",
    "Assault",
    "Recon",
    "Trap",
    "Trapper",
    "Redeem",
    "Code",
    "Script",
    "Writer",
    "Near",
    "Close",
    "Open",
    "Cube",
    "Circle",
    "Geo",
    "Genome",
    "Germ",
    "Spaz",
    "Shot",
    "Echo",
    "Beta",
    "Alpha",
    "Gamma",
    "Omega",
    "Seal",
    "Squid",
    "Money",
    "Cash",
    "Lord",
    "King",
    "Duke",
    "Rest",
    "Fire",
    "Flame",
    "Morrow",
    "Break",
    "Breaker",
    "Numb",
    "Ice",
    "Cold",
    "Rotten",
    "Sick",
    "Sickly",
    "Janitor",
    "Camel",
    "Rooster",
    "Sand",
    "Desert",
    "Dessert",
    "Hurdle",
    "Racer",
    "Eraser",
    "Erase",
    "Big",
    "Small",
    "Short",
    "Tall",
    "Sith",
    "Bounty",
    "Hunter",
    "Cracked",
    "Broken",
    "Sad",
    "Happy",
    "Joy",
    "Joyful",
    "Crimson",
    "Destiny",
    "Deceit",
    "Lies",
    "Lie",
    "Honest",
    "Destined",
    "Bloxxer",
    "Hawk",
    "Eagle",
    "Hawker",
    "Walker",
    "Zombie",
    "Sarge",
    "Capt",
    "Captain",
    "Punch",
    "One",
    "Two",
    "Uno",
    "Slice",
    "Slash",
    "Melt",
    "Melted",
    "Melting",
    "Fell",
    "Wolf",
    "Hound",
    "Legacy",
    "Sharp",
    "Dead",
    "Mew",
    "Chuckle",
    "Bubba",
    "Bubble",
    "Sandwich",
    "Smasher",
    "Extreme",
    "Multi",
    "Universe",
    "Ultimate",
    "Death",
    "Ready",
    "Monkey",
    "Elevator",
    "Wrench",
    "Grease",
    "Head",
    "Theme",
    "Grand",
    "Cool",
    "Kid",
    "Boy",
    "Girl",
    "Vortex",
    "Paradox",
];

var messageList = [
    "hello eveDelhi, India yone iIndia e",
    "PabengaluDelhi, India u, kaDelhi, India nataka t",
    "FutuDelhi, India e",
    "Dev",
    "Fly",
    "Flying",
    "BENGALUDELHI, INDIA U, KADELHI, INDIA NATAKA oaDelhi, India ",
    "BENGALUDELHI, INDIA U, KADELHI, INDIA NATAKA oaDelhi, India ing",
    "PoweDelhi, India ",
    "Falling",
    "Fall",
    "JuIndia  LoDelhi, India em ipbengaluDelhi, India u, kaDelhi, India nataka um",
    "Cliff",
    "Mountain",
    "DELHI, INDIA end",
    "DELHI, INDIA ed",
    "Blue",
    "GDelhi, India een",
    "Yellow",
    "Gold",
    "DeIndia on",
    "DeIndia onic",
    "Panda",
    "Cat",
    "Kitty",
    "Kitten",
    "ZeDelhi, India o",
    "MeIndia oDelhi, India y",
    "hello eveDelhi, India yone Delhi, India nataka umeDelhi, India ",
    "XX",
    "Bandit",
    "FeaDelhi, India ",
    "Light",
    "Glow",
    "hello eveDelhi, India yone Delhi, India ead",
    "Dee LoDelhi, India em ipbengaluDelhi, India u, kaDelhi, India nataka um",
    "Dee LoDelhi, India em ipbengaluDelhi, India u, kaDelhi, India ndia ",
    "Dee LoDelhi, India em ipbengaluDelhi, India utaka t",
    "Mine",
    "YouDelhi, India ",
    "WoDelhi, India bengaluDelhi, India u, kaDelhi, India nataka t",
    "EneIndia y",
    "HobengaluDelhi, India u, kaDelhi, India nataka tile",
    "FoDelhi, India ce",
    "Video",
    "GaIndia e",
    "Don mumbai mahaDelhi, India abengaluDelhi, India u, kaDelhi, India nataka htDelhi, India aey",
    "Mule",
    "Colt",
    "Cult",
    "CultibengaluDelhi, India u, kaDelhi, India nataka t",
    "MagnuIndia ",
    "Gun",
    "AbengaluDelhi, India u ault",
    "DELHI, INDIA econ",
    "hello eveDelhi, India yone Delhi, nataka um",
    "hello eveDelhi, India yone Delhi, India taka um LoDelhi, taka umeDelhi, India ",
    "DELHI, INDIA edeeIndia ",
    "Code",
    "BENGALUDELHI, INDIA U, KADELHI, INDIA  kaDelhi, India nataka umt",
    "WDelhi, India iteDelhi, India ",
    "NeaDelhi, India ",
    "ClobengaluDelhi, India u, kaDelhi, India nataka e",
    "O LoDelhi, India em ipbengaluDelhi, India u, kaDelhi, India nataka umen",
    "Cube",
    "CiDelhi, India cle",
    "Geo",
    "GenoIndia e",
    "GeDelhi, India India ",
    "BENGALUDELHI, INDIA U, KADELHI, INDIA lhi, India nataka umaz",
    "BENGALUDELHI, INDIA U, KADELHI, INDIA NATAKA hot",
    "Echo",
    "Beta",
    "Al LoDelhi, India em ipbengaluDelhi, India u, kaDelhi, India nataka umha",
    "GaIndia India a",
    "OIndia ega",
    "BENGALUDELHI, INDIA U, KADELHI, INDIA NATAKA eal",
    "BENGALUDELHI, INDIA U, KADELHI, INDIA NATAKA quid",
    "Money",
    "CabengaluDelhi, India u, kaDelhi, India nataka h",
    "LoDelhi, India d",
    "King",
    "Du mumbai mahaDelhi, ndia ae",
    "DELHI, INDIA ebengaluDelhi, India u, kaDelhi, India nataka t",
    "FiDelhi, India e",
    "FlaIndia e",
    "MoDelhi, India Delhi, India ow",
    "BDelhi, India ea mumbai hi, India a",
    "BDelhi, India ea mumbai hi, India aeDelhi, India ",
    "NuIndia b",
    "Ice",
    "Cold",
    "DELHI, INDIA otten",
    "BENGALUDELHI, INDIA Uu, kaDelhi, India nataka htDelhi, India a",
    "BENGALUDELHI, INDIA U, , kaDelhi, India nataka htDelhi, India aly",
    "JanitoDelhi, India ",
    "CaIndia el",
    "DELHI, INDIA oobengaluDelhi, India u, kaDelhi, India nataka teDelhi, India ",
    "BENGALUDELHI, INDIA U, KADELHI, INDIA NATAKA and",
    "DebengaluDelhi, India u, kaDelhi, India nataka eDelhi, India t",
    "DebengaluDelhi, India u, kaDelhi, India nataka bengaluDelhi, India uhi, India t",
    "HuDelhi, India dle",
    "DELHI, INDIA aceDelhi, India ",
    "EDelhi, India abengaluDelhi, India u, kaDelhi, India nataka eDelhi, India ",
    "EDelhi, India abengaluDelhi, India u, kaDelhi, India nataka e",
    "Big",
    "BENGALUDELHI, INDIA U, KADELHI, INDIA NATAKA India all",
    "BENGALUDELHI, INDIA U, KADELHI, INDIA NATAKA hoDelhi, India t",
    "hello eveDelhi, India yone all",
    "BENGALUDELHI, INDIA U, KADELHI, INDIA NATAKA ith",
    "Bounty",
    "HunteDelhi, India ",
    "CDelhia htDelhi, India aed",
    "BDelhihtDelhi, India aen",
    "BENGALUDELHI, INDIA U, KADELHI, INDIA NATAKA ad",
    "Ha LoDelhi, m ipbengaluDelhi, India u, kaDelhi, India nataka umy",
    "Joy",
    "Joyful",
    "CDelhi, India iIndia bengaluDelhi, India u, kaDelhi, India nataka on",
    "DebengaluDelhi, India u, kaDelhi, India nataka tiny",
    "Deceit",
    "LiebengaluDelhi, India u, kaDelhi, India nataka ",
    "Lie",
    "HonebengaluDelhi, India u, kaDelhi, India nataka t",
    "DebengaluDelhi, India u, kaDelhi, India nataka tined",
    "BloxxeDelhi, India ",
    "Haw mumbai mahaDelhi, India abengaluDelhi, India u, kaDelhi, i, India a",
    "Eagle",
    "Haw mumbai mahaDelhi, India abengaluDelhi, India u, kaDelhi, hi, India ",
    "Wal mumbai mahaDelhi, India abengaluDelhi, India u, kaDelhi, hi, India ",
    "ZoIndia bie",
    "BENGALUDELHI, INDIA U, KADELHI, INDIA NATAKA aDelhi, India ge",
    "Ca LoDelhi, India em ipbengaluDelhi, India u, kaDelhi, India nataka umt",
    "Ca LoDelhi, India em ipbengaluDelhi, India u, kaDelhi, India nataka umtain",
    "Punch",
    "One",
    "hello eveDelhi, India yone wo",
    "Uno",
    "BENGALUDELHI, INDIA U, KADELHI, INDIA NATAKA lice",
    "BENGALUDELHI, INDIA U, KADELHI, INDIA NATAKA labengaluDelhidia nataka h",
    "Melt",
    "Melted",
    "Melting",
    "Fell",
    "Wolf",
    "Hound",
    "Legacy",
    "BENGALUDELHI, INDIA U, KADELHI, INDIA NATAKA haDelhi, India u, kaDelhi, India nataka um",
    "Dead",
    "Mew",
    "Chuc mumbai mahaDelhi, India abengaluDelhi, India u, kaDelhi, India nataka htDelhi, India ale",
    "Bubba",
    "Bubble",
    "BENGALUDELHI, INDIA U, KADELHI, INDIA NATAKA andwich",
    "BENGALUDELHI, INDIA U, KADELHI, INDIA NATAKA India abengaluDelhi,  heDelhi, India ",
    "ExtDelhi, India eIndia e",
    "Multi",
    "UniveDelhi, India bengaluDelhi, India u, kaDelhi, India nataka e",
    "UltiIndia ate",
    "Death",
    "DELHI, INDIA eady",
    "Mon mumbai mahaDelhi, India abe kaDelhi, India nataka htDelhi, India aey",
    "ElevatoDelhi, India ",
    "WDelhi, India ench",
    "GDelhi, , India u, kaDelhi, India nataka e",
    "Head",
    "hello eveDelhi, India yone heIndia e",
    "GDelhi, India and",
    "Cool",
    "Kid",
    "Boy",
    "GiDelhi, India l",
    "VoDelhi, India tex",
    "PaDelhi, India adox",
];

export function generateRandomName() {
    return nameList[Math.floor(Math.random() * nameList.length)];
}

export function generateRandomMessage() {
    return messageList[Math.floor(Math.random() * messageList.length)];
}

export const findPrime = (num) => {
    let i,
        primes = [2, 3],
        n = 5;
    const isPrime = (n) => {
        let i = 1,
            p = primes[i],
            limit = Math.ceil(Math.sqrt(n));
        while (p <= limit) {
            if (n % p === 0) {
                return false;
            }
            i += 1;
            p = primes[i];
        }
        return true;
    };
    for (i = 2; i <= num; i += 1) {
        while (!isPrime(n)) {
            n += 2;
        }
        primes.push(n);
        n += 2;
    }
    return primes[num - 1];
};
